  - name: replace httpd.conf
    copy: src={{role_path}}/files/httpd.conf dest=/etc/httpd/conf/httpd.conf

  - name: Apache start
    service:
      name: httpd
      state: restarted
      enabled: yes
